version: "3"

services:
  db:
    image: postgres:13-alpine
    container_name: poetry_db
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    container_name: poetry_redis
    ports:
      - "6379:6379"
